# Generated by Django 3.2.6 on 2021-09-30 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tester', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town_name', models.CharField(max_length=64, verbose_name='town_name')),
            ],
        ),
        migrations.CreateModel(
            name='EducationsUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.educationplace')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tester.group')),
                ('town_name_of_EduPlace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.town')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='educationplace',
            name='town',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.town'),
        ),
    ]
